### ISSUE TITLE
The C compiler identification is unknown

### ISSUE THREAD

**Issue by babasa** [enwi/minerpp#1]
```
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:2 (project):
  The CMAKE_C_COMPILER:

    usr/bin/gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/minerpp/bin/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/minerpp/bin/CMakeFiles/CMakeError.log".
Makefile:236: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
```

so when i try to install everything is good until i got in this step " _make -j<number of threads>_"
and got the error i posting above? can someone help me pls, thank you guys

**Comment by babasa** [comment]
so i just take precompiled instead and it can be running

**Comment by enwi** [comment]
Do you have gcc installed? What's the output of `gcc --version`?

**Comment by babasa** [comment]
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609

this one

**Comment by enwi** [comment]
Then I would recommend specifying the compiler when executing cmake like `cmake .. -DCMAKE_C_COMPILER=/path/to/gcc`. Where you should replace "/path/to/gcc" with one of the paths of the output of `whereis gcc`.
