### ISSUE TITLE
[PollLocal] Could not parse answer: parse error - unexpected '<'

### ISSUE THREAD

**Issue by babasa** [enwi/minerpp#2]
got error message "[PollLocal] Could not parse answer: parse error - unexpected '<'"

how can i fix it? thanks

**Comment by enwi** [comment]
Does it happen all the time or only from time to time? If it only happens from time to time, don't worry about it.

**Comment by babasa** [comment]
ok thank you, its just happen rarely, and still got deadline so seems not a problem
